/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from "./Counter.sol";
export type { counterSol };
import type * as voteSol from "./Vote.sol";
export type { voteSol };
export type { Lock } from "./Lock";
export type { MultiElectionVoting } from "./MultiElectionVoting";
