/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterSol from "./Counter.sol";
export * as voteSol from "./Vote.sol";
export { Lock__factory } from "./Lock__factory";
export { MultiElectionVoting__factory } from "./MultiElectionVoting__factory";
